name: MyBrowserApp
options:
  bundleIdPrefix: com.lskyz
  deploymentTarget:
    iOS: "15.0"  # SwiftUI 사용을 고려해 iOS 15 이상
targets:
  MyBrowserApp:
    type: application
    platform: iOS
    sources:
      - path: MyBrowserApp
    settings:
      base:
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
    info:
      path: MyBrowserApp/Info.plist
