name: MyBrowserApp
options:
  bundleIdPrefix: com.lskyz
  deploymentTarget:
    iOS: "15.0"
targets:
  MyBrowserApp:
    type: application
    platform: iOS
    sources:
      - path: MyBrowserApp
    settings:
      base:
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        SWIFT_VERSION: "5.0"              # 추가
        ALWAYS_SEARCH_USER_PATHS: NO      # 추가
    scheme:
      name: MyBrowserApp
      build:
        targets:
          - MyBrowserApp
      archive:
        config: Release
