name: MyBrowserApp
options:
  bundleIdPrefix: com.lskyz
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
  groupSortPosition: top

configs:
  Debug:
    buildSettings:
      ALWAYS_SEARCH_USER_PATHS: NO
  Release:
    buildSettings:
      ALWAYS_SEARCH_USER_PATHS: NO

targets:
  MyBrowserApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: MyBrowserApp
    resources:
      - path: MyBrowserApp/Assets.xcassets
      - path: MyBrowserApp/LaunchScreen.storyboard
    info:
      path: MyBrowserApp/Info.plist
      properties:
        CFBundleIdentifier: com.lskyz.MyBrowserApp
        CFBundleName: MyBrowserApp
        CFBundleVersion: "1.0"
        CFBundleShortVersionString: "1.0"
        CFBundlePackageType: "APPL"
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: "LaunchScreen"
    settings:
      base:
        SWIFT_VERSION: "5.0"
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        ALWAYS_SEARCH_USER_PATHS: NO
        INSTALL_PATH: "$(BUILT_PRODUCTS_DIR)/MyBrowserApp.app"
        PRODUCT_BUNDLE_IDENTIFIER: com.lskyz.MyBrowserApp
        PRODUCT_NAME: MyBrowserApp
    scheme:
      name: MyBrowserApp
      build:
        targets:
          - MyBrowserApp
      archive:
        config: Release