name: MyBrowserApp
options:
  bundleIdPrefix: com.lskyz
  deploymentTarget:
    iOS: "15.0"
targets:
  MyBrowserApp:
    type: application
    platform: iOS
    sources:
      - path: MyBrowserApp
    settings:
      base:
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
    scheme:
      build:
        targets:
          MyBrowserApp: [archive]
    info:
      path: MyBrowserApp/Info.plist
